// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cardata_api_v3.Models;

namespace cardata_api_v3.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cardata_api_v3.Models.CarItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Co2Eemissions")
                        .HasColumnType("int");

                    b.Property<string>("Co2EemissionsUm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EngineYearF")
                        .HasColumnType("int");

                    b.Property<int?>("EngineYearI")
                        .HasColumnType("int");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Generation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxPowerBhp")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPowerKw")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTorqueNm")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModelYearF")
                        .HasColumnType("int");

                    b.Property<int?>("ModelYearI")
                        .HasColumnType("int");

                    b.Property<string>("PhotoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopSpeedKmph")
                        .HasColumnType("int");

                    b.Property<double?>("Zero100")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CarItems");
                });
#pragma warning restore 612, 618
        }
    }
}
